version: '3.9'

services:
  api-dev-books:
    container_name: rubies99
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:8002
    volumes:
      - ./:/app 

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017    
